export const types = {
  ASSIGN_COURSE: 'ASSIGN_COURSE',
  SET_LOADING: 'SET_LOADING',
  CREATE_COURSE: 'CREATE_COURSE',
  GET_COURSES: 'GET_COURSES',
  GET_COURSE: 'GET_COURSE',
  ASSIGNED_STUDENT: "aSSIGNED_STUDENT"
};
