export const types = {
  ASSIGN_COURSE: 'ASSIGN_COURSE',
  SET_LOADING: 'SET_LOADING',
  CREATE_COURSE: 'CREATE_COURSE',
  GET_COURSES: 'GET_COURSES',
  GET_COURSE: 'GET_COURSE',
  ASSIGNED_STUDENT: 'aSSIGNED_STUDENT',
  CLEAR_COURSES: 'CLEAR_COURSES',
  ASSIGN_COURSE_TO_CLASS: 'ASSIGN_COURSE_TO_CLASS',
};
