export const types = {
  GET_STUDENTS: 'GET_STUDENTS',
  GET_STUDENT: 'GET_STUDENT',
  UPDATE_STUDENT: 'UPDATE_STUDENT',
  DELETE_STUDENT: 'DELETE_STUDENT',
  CREATE_STUDENT: 'CREATE_STUDENT',
  GET_STUDENTS_DEPT: 'GET_STUDENTS_DEPT',
  SEARCH_STUDENTS: 'SEARCH_STUDENTS',
  IS_SEARCHING_STUDENTS: 'IS_SEARCHING_STUDENTS',
  CLEAR_STUDENTS: 'CLEAR_STUDENTS',
};
