export const types = {
  GET_ROOMS: 'GET_ROOMS',
  GET_ROOM: 'GET_ROOM',
  UPDATE_ROOM: 'UPDATE_ROOM',
  DELETE_ROOM: 'DELETE_ROOM',
  CREATE_ROOM: 'CREATE_ROOM',
  ASSIGN_ROOM: 'ASSIGN_ROOM',
  CLEAR_ROOM: 'CLEAR_ROOM',
  ROOM_LOADING: 'ROOM_LOADING',
};
